import pymysql
from tkinter import messagebox
from tkinter import ttk
import datetime
import tkinter
from tkinter import*
def showbookupdate():
    t=tkinter.Tk()
    t.geometry('700x700')
    t.title("BookingData")
    t.configure(bg='#93C572')
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='cms')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        xe=e5.get()
        sql="update bookingdataa set parcelno=%s, catid=%s, cityid=%s, dateofbooking=%s where custid=%s"%(xb,xc,xd,xe,xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo("hi","updated")
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='cms')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select parcelno,catid,cityid,dateofbooking from bookingdataa where custid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,str(data[2]))
        e5.insert(0,data[3])
        db.close()
    def close():
        t.destroy()
    head=Label(t,text='BOOKING DATA',bg='#f2ede7',font=('segoe UI',18,'bold'))
    head.place(x=280,y=10)
    a=Label(t,text='customerid',bg='#f2ede7',font=('segoe UI',12,'bold'))
    a.place(x=80,y=100)
    e1=ttk.Combobox(t,width=27)
    e1['values']=list(range(101,121))
    e1.place(x=300,y=100)
    b=Label(t,text='parcelno',bg='#f2ede7',font=('segoe UI',12,'bold'))
    b.place(x=80,y=150)
    e2=ttk.Combobox(t,width=27)
    e2['values']=list(range(301,321))
    e2.place(x=300,y=150)
    d=Label(t,text='catid',bg='#f2ede7',font=('segoe UI',12,'bold'))
    d.place(x=80,y=200)
    e3=ttk.Combobox(t,width=27)
    e3['values']=list(range(501,521))
    e3.place(x=300,y=200)
    f=Label(t,text='cityid',bg='#f2ede7',font=('segoe UI',12,'bold'))
    f.place(x=80,y=250)
    e4=ttk.Combobox(t,width=27)
    e4['values']=list(range(701,721))
    e4.place(x=300,y=250)
    g=Label(t,text='dateofbooking',bg='#f2ede7',font=('segoe UI',12,'bold'))
    g.place(x=80,y=300)
    e5=Entry(t,width=20)
    e5.place(x=300,y=300)
    today=datetime.date.today()
    e5.insert(0,str(today))
    btn1=Button(t,text='Update',command=updatedata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn1.place(x=100,y=400)
    btn2=Button(t,text='Find',command=finddata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn2.place(x=200,y=400)
    btn3=Button(t,text='Close',command=close,bg='#e53935',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn3.place(x=300,y=400)
    
    t.mainloop()