import pymysql
from tkinter import messagebox
from tkinter import ttk
import tkinter
from tkinter import*
def showcityupdate():
    t = tkinter.Tk()
    t.geometry('700x700')
    t.title("CityData")
    t.configure(bg='#93C572')
    def updatedata():
        db = pymysql.connect(host='localhost', user='root', password='root', database='cms')
        cur = db.cursor()
        xa = int(e1.get())
        xb = e2.get()
        xc = e3.get()
        xd = int(e4.get())
        sql = "update citydata set city_name=%s, state=%s, pincode=%s where cityid=%s"
        val = (xb, xc, xd, xa)
        cur.execute(sql, val)
        db.commit()
        db.close()
        messagebox.showinfo("Hi", "Updated")
        e1.delete(0, 100)
        e2.delete(0, 100)
        e3.delete(0, 100)
        e4.delete(0, 100)
    def finddata():
        db = pymysql.connect(host='localhost', user='root', password='root', database='cms')
        cur = db.cursor()
        xa = int(e1.get())
        sql = "select city_name, state, pincode from citydata where cityid = %s"
        cur.execute(sql, (xa,))
        data = cur.fetchone()
        db.close()
        e2.delete(0, END)
        e3.delete(0, END)
        e4.delete(0, END)
    
        e2.insert(0, data[0])
        e3.insert(0, data[1])
        e4.insert(0, str(data[2]))
    def close():
        t.destroy()
    head=Label(t,text='CITY DATA',bg='#f2ede7',font=('segoe UI',18,'bold'))
    head.place(x=280,y=10)
    a=Label(t,text='cityid',bg='#f2ede7',font=('segoe UI',12,'bold'))
    a.place(x=80,y=100)
    e1=ttk.Combobox(t,width=27)
    e1['values']=list(range(201,221))
    e1.place(x=300,y=100)
    b=Label(t,text='cityname',bg='#f2ede7',font=('segoe UI',12,'bold'))
    b.place(x=80,y=150)
    e2=ttk.Combobox(t,width=27)
    e2['values']=('Agra','Delhi','Noida','Mumbai','Chennai','Jaipur','Mathura')
    e2.place(x=300,y=150)
    d=Label(t,text='state',bg='#f2ede7',font=('segoe UI',12,'bold'))
    d.place(x=80,y=200)
    e3=ttk.Combobox(t,width=27)
    e3['values']=('Arunachal Pradesh','Himmachal Pradesh','Uttar Pradesh','UttraKhand','Maharastra','WestBengal','Gujarat')
    e3.place(x=300,y=200)
    f=Label(t,text='pincode',bg='#f2ede7',font=('segoe UI',12,'bold'))
    f.place(x=80,y=250)
    e4=Entry(t,width=30)
    e4.place(x=300,y=250)
    btn1=Button(t,text='update',command=updatedata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=15,height=1)
    btn1.place(x=100, y=320)
    btn2=Button(t,text='Find',command=finddata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=15,height=1)
    btn2.place(x=100, y=380)
    btn3=Button(t,text='Close',command=close,bg='#e53935',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn3.place(x=230,y=380)
    t.mainloop()