import pymysql
from tkinter import messagebox
from tkinter import ttk
import tkinter
import datetime
from tkinter import *
def showdelinsert():
    t=tkinter.Tk()
    t.geometry('700x700')
    t.title("DeliveryData")
    t.configure(bg='orange')
    def savedata():
        if len(e1.get())==0 or len(e2.get())==0 or len(e3.get())==0 or len(e4.get())==0 or len(e5.get())==0:
            messagebox.showinfo('Hi','please fill all data')
        else:
            db = pymysql.connect(host='localhost', user='root', password='root', database='cms')
            cur = db.cursor()
            xa = int(e1.get())
            xb = int(e2.get())
            xc = int(e3.get())
            xd = int(e4.get())
            xe = e5.get()
            sql = "insert into deliverdata values (%d, %d, %d, %d, '%s')" % (xa, xb, xc, xd, xe)
            cur.execute(sql)
            db.commit()
            db.close()
            messagebox.showinfo("Hi", "savedsuccessfully")
            e1.delete(0, END)
            e2.delete(0, END)
            e3.delete(0, END)
            e4.delete(0, END)
            e5.delete(0, END)
    def close():
        t.destroy()
    head=Label(t,text='DELIVER DATA',bg='orange',fg='cyan',font=('segoe UI',18,'bold'))
    head.place(x=280,y=10)
    a=Label(t,text='Parcelno',bg='orange',font=('segoe UI',12,'bold'))
    a.place(x=100,y=100)
    e1=ttk.Combobox(t,width=27)
    e1['values']=list(range(301,331))
    e1.place(x=300,y=100)
    b=Label(t,text='Custid',bg='orange',font=('segoe UI',12,'bold'))
    b.place(x=100,y=150)
    e2=ttk.Combobox(t,width=27)
    e2['values']=list(range(101,131))
    e2.place(x=300,y=150)
    d=Label(t,text='Catid',bg='orange',font=('segoe UI',12,'bold'))
    d.place(x=100,y=200)
    e3=ttk.Combobox(t,width=27)
    e3['values']=list(range(501,531))
    e3.place(x=300,y=200)
    f=Label(t,text='Cityid',bg='orange',font=('segoe UI',12,'bold'))
    f.place(x=100,y=250)
    e4=ttk.Combobox(t,width=27)
    e4['values']=list(range(701,731))
    e4.place(x=300,y=250)
    g=Label(t,text='DateofDelivery',bg='orange',font=('segoe UI',12,'bold'))
    g.place(x=100,y=300)
    e5=Entry(t,width=30)
    e5.place(x=300,y=300)
    today=datetime.date.today()
    e5.insert(0,str(today))
    btn1=Button(t,text='Save',command=savedata,bg='#2e7d32',fg='#ffffff',font=('calibri',11,'bold'),width=10,height=1)
    btn1.place(x=300,y=400)
    btn2=Button(t,text='Close',command=close,bg='#e53935',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn2.place(x=400,y=400)
    t.mainloop()