import pymysql
from tkinter import messagebox
import tkinter
from tkinter import ttk
from tkinter import*
def showpaupdate():
    t=Tk()
    t.geometry('700x700')
    t.title("ParcelCategory")
    t.configure(bg='magenta')
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='cms')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=float(e3.get())
        xd=float(e4.get())
        sql="update parcelcategory set catname='%s',minweight=%f,maxweight=%f where catid=%d"%(xb,xc,xd,xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo("Hi","Updated")
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='cms')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select catname,minweight,maxweight from parcelcategory where catid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,str(data[1]))
        e4.insert(0,str(data[2]))
        db.close()
    def close():
        t.destroy()
    head=Label(t,text='PARCELCATEGORY',bg='yellow',fg='black',font=('segoe UI',18,'bold'))
    head.place(x=280,y=10)
    a=Label(t,text='catid',bg='magenta',font=('segoe UI',18,'bold'))
    a.place(x=100,y=100)
    e1=ttk.Combobox(t,width=27)
    e1['values']=list(range(501,521))
    e1.place(x=300,y=100)
    b=Label(t,text='catname',bg='magenta',font=('segoe UI',18,'bold'))
    b.place(x=100,y=150)
    e2=Entry(t,width=30)
    e2.place(x=300,y=150)
    c=Label(t,text='minweight',bg='magenta',font=('segoe UI',18,'bold'))
    c.place(x=100,y=200)
    e3=ttk.Combobox(t,width=27)
    e3['values']=list(range(50,500))
    e3.place(x=300,y=200)
    d=Label(t,text='maxweight',bg='magenta',font=('segoe UI',18,'bold'))
    d.place(x=100,y=250)
    e4=ttk.Combobox(t,width=27)
    e4['values']=list(range(500,1000))
    e4.place(x=300,y=250)
    btn=Button(t,text='Update',command=updatedata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn.place(x=260,y=350)
    btn1=Button(t,text='Find',command=finddata,bg='#1565c0',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn1.place(x=360,y=350)
    btn2=Button(t,text='Close',command=close,bg='#e53935',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn2.place(x=460,y=350)
    t.mainloop()