import pymysql
from tkinter import messagebox
import tkinter
from tkinter import ttk
from tkinter import*
def showparinsert():
    t=Tk()
    t.geometry('700x700')
    t.title("ParcelCharge")
    t.configure(bg='crimson')
    def savedata():
        if len(c1.get())==0 or len(e2.get())==0 or len(e3.get())==0 or len(e4.get())==0:
            messagebox.showinfo('Hi','please fill all data')
        else:
            db=pymysql.connect(host='localhost',user='root',password='root',database='cms')
            cur=db.cursor()
            xa=int(c1.get())
            xb=e2.get()
            xc=float(e3.get())
            xd=float(e4.get())
            sql="insert into parcelcharge values(%d,'%s',%f,%f)"%(xa,xb,xc,xd)
            cur.execute(sql)
            db.commit()
            db.close()
            messagebox.showinfo("Hi","Saved")
            c1.delete(0,100)
            e2.delete(0,100)
            e3.delete(0,100)
            e4.delete(0,100)
    def close():
        t.destroy()
    head=Label(t,text='PARCEL CHARGE',bg='yellow',fg='black',font=('segoe UI',18,'bold'))
    head.place(x=280,y=10)
    a=Label(t,text='catid',bg='crimson',font=('segoe UI',18,'bold'))
    a.place(x=100,y=100)
    c1=ttk.Combobox(t,width=27)
    c1['values']=list(range(501,521))
    c1.place(x=300,y=100)
    b=Label(t,text='subcategory',bg='crimson',font=('segoe UI',18,'bold'))
    b.place(x=100,y=150)
    e2=Entry(t,width=30)
    e2.place(x=300,y=160)
    c=Label(t,text='mincharges',bg='crimson',font=('segoe UI',18,'bold'))
    c.place(x=100,y=200)
    e3=Entry(t,width=30)
    e3.place(x=300,y=210)
    d=Label(t,text='distancecharges',bg='crimson',font=('segoe UI',18,'bold'))
    d.place(x=100,y=250)
    e4=Entry(t,width=30)
    e4.place(x=300,y=260)
    btn=Button(t,text='Save',command=savedata,bg='#2e7d32',fg='#ffffff',font=('calibri',11,'bold'),width=10,height=1)
    btn.place(x=100,y=360)
    btn2=Button(t,text='Close',command=close,bg='#e53935',fg='white',font=('calibri',11,'bold'),width=10,height=1)
    btn2.place(x=230,y=360)
    t.mainloop()